export const SET_ALL_BOOKS = 'SET_ALL_BOOKS';
export const SET_CURRENT_BOOK = 'SET_CURRENT_BOOK';
export const CLEAR_CURRENT_BOOK = 'CLEAR_CURRENT_BOOK';

export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

export const SET_CATEGORIES = 'SET_CATEGORIES';
